# Usa l'immagine ufficiale di RabbitMQ come base
FROM rabbitmq:3.8-management

# Copia i file di configurazione personalizzati, se necessario
# COPY rabbitmq.config /etc/rabbitmq/rabbitmq.config

# Esponi le porte necessarie per RabbitMQ (AMQP e console di gestione)
EXPOSE 5672 15672

# Puoi aggiungere ulteriori istruzioni qui, se necessario
